### PR TITLE
Fix trailing comments after final statement in a function

### LINKED ISSUE #62: A comment at the end of a function gets parsed outside of the function
In code like this:

```gdscript
func do_thing() -> void:
	if true:
		pass
		# TODO: Implement thing
```

The comment gets parsed as if it was at the top-level/outside the function body.

### PR DESCRIPTION
**Pull request by TranquilMarmot**
Fixes #62

It feels like this is a little more complex than it needs to be. The problem is definitely inside of `scanner.c`.

### CODE REVIEW

File: src/scanner.c [hunk 1]
```diff
@@ -274,13 +274,113 @@ bool tree_sitter_gdscript_external_scanner_scan(void *payload, TSLexer *lexer,
...
+                            skip(lexer);
+                        } else if (lexer->lookahead == ' ') {
+                            next_indent++;
+                            skip(lexer);
+                        } else if (lexer->lookahead == '\t') {
+                            next_indent += 8;
+                            skip(lexer);
+                        } else if (lexer->lookahead == '\r' || lexer->lookahead == '\f') {
+                            next_indent = 0;
+                            skip(lexer);
```
Comment (TranquilMarmot) [inline src/scanner.c:359]: These are copied from here:

https://github.com/PrestonKnopp/tree-sitter-gdscript/blob/2ada1c665f3516bd72f8c00568018963250e2055/src/scanner.c#L255-L267

Not sure if we want to make this a reusable function, something like... `skip_whitespace`?

**Review by NathanLovato — COMMENTED** [review]
Looking great to me. It's not shocking to me that this is "complicated" like this because of the way this parser system works. The code used to be longer than that.

Because this parser is forward only and the scanner gets ran only at specific points in scanning/parsing the code, it naturally leads to some extra parsing complexity at times. It'd be way easier if you could keep a stack of partially parsed tokens (like a function that's not closed yet), then when something looks like a new source level definition or end of file you backtrack and you close the previous function, for example.

Tree sitter generally just does not handle indent-based parsing at all for you. Thank you very much for taking the time to work on this!

File: src/scanner.c (hunk 1 above)
Comment (PrestonKnopp) [reply src/scanner.c:359]: I second this!

File: src/scanner.c [hunk 2]
```diff
@@ -274,13 +274,113 @@ bool tree_sitter_gdscript_external_scanner_scan(void *payload, TSLexer *lexer,
...
             }
 
+            // Store the current indentation level before processing the comment
+            uint32_t comment_indent_length = indent_length;
+            
+            // If we're in a situation where we need to emit a DEDENT first,
+            // don't consume the comment - let the DEDENT be processed first
+            if (scanner->indents->len > 0) {
+                uint16_t current_indent_length = VEC_BACK(scanner->indents);
+                if (valid_symbols[DEDENT] && indent_length < current_indent_length) {
```
Comment (PrestonKnopp) [inline src/scanner.c:284]: Can we move the `valid_symbols[DEDENT]` check to the outer if condition?

```suggestion
            if (valid_symbols[DEDENT] && scanner->indents->len > 0) {
                uint16_t current_indent_length = VEC_BACK(scanner->indents);
                if (indent_length < current_indent_length) {
```

**Comment by PrestonKnopp** [comment]
This is lookin good. Thank you for tackling this issue! I will be able to test it some more tomorrow.
